// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/InboxScreen.tsx": () => import("../components/mockups/InboxScreen.tsx"),
  "./components/mockups/PoolScreen.tsx": () => import("../components/mockups/PoolScreen.tsx"),
  "./components/mockups/QuizScreen.tsx": () => import("../components/mockups/QuizScreen.tsx")
};
